package coldstorage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class sensor implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String roomName;
   private java.lang.String sensorType;
   private java.lang.Double reading;
   private java.lang.String alert;
   private java.lang.String status;
   private java.lang.String color;
   private java.lang.String notification;

   public sensor()
   {
   }

   public java.lang.String getRoomName()
   {
      return this.roomName;
   }

   public void setRoomName(java.lang.String roomName)
   {
      this.roomName = roomName;
   }

   public java.lang.String getSensorType()
   {
      return this.sensorType;
   }

   public void setSensorType(java.lang.String sensorType)
   {
      this.sensorType = sensorType;
   }

   public java.lang.Double getReading()
   {
      return this.reading;
   }

   public void setReading(java.lang.Double reading)
   {
      this.reading = reading;
   }

   public java.lang.String getAlert()
   {
      return this.alert;
   }

   public void setAlert(java.lang.String alert)
   {
      this.alert = alert;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.String getColor()
   {
      return this.color;
   }

   public void setColor(java.lang.String color)
   {
      this.color = color;
   }

   public java.lang.String getNotification()
   {
      return this.notification;
   }

   public void setNotification(java.lang.String notification)
   {
      this.notification = notification;
   }

   public sensor(java.lang.String roomName, java.lang.String sensorType,
         java.lang.Double reading, java.lang.String alert,
         java.lang.String status, java.lang.String color,
         java.lang.String notification)
   {
      this.roomName = roomName;
      this.sensorType = sensorType;
      this.reading = reading;
      this.alert = alert;
      this.status = status;
      this.color = color;
      this.notification = notification;
   }

}